CREATE DATABASE HomeTask_DDL_DML ON PRIMARY
    (NAME = 'HomeTask_DDL_DML.mdf', FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HomeTask_DDL_DML.mdf', SIZE = 167872 KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384 KB)
    LOG ON
    (NAME = 'HomeTask_DDL_DML_Log.ldf', FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HomeTask_DDL_DML_Log.ldf', SIZE = 2048 KB , MAXSIZE = 2048 GB , FILEGROWTH = 16384 KB)


